#!/usr/bin/env python3
"""Generate a deterministic MariaDB import from a WordPress SQLite database.

The generated SQL preserves primary keys and PHP-serialized values byte-for-byte.
SQLite integration metadata tables are intentionally excluded.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import math
import re
import sqlite3
from pathlib import Path
from typing import Any, TextIO


SAFE_IDENTIFIER = re.compile(r"^[A-Za-z0-9_]+$")

GOOGLE_REVIEW_TABLES = """
CREATE TABLE IF NOT EXISTS `wp_grp_google_place` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `place_id` varchar(255) NOT NULL,
  `name` text NOT NULL,
  `photo` text NULL,
  `icon` text NULL,
  `address` text NULL,
  `rating` double NULL,
  `url` text NULL,
  `map_url` text NULL,
  `website` text NULL,
  `review_count` bigint NULL,
  `updated` bigint NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `grp_place_id` (`place_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `wp_grp_google_review` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `google_place_id` bigint unsigned NOT NULL,
  `review_id` varchar(255) NOT NULL,
  `rating` int NOT NULL,
  `text` longtext NULL,
  `time` bigint NOT NULL,
  `url` text NULL,
  `language` varchar(32) NULL,
  `author_name` text NULL,
  `author_url` varchar(512) NULL,
  `profile_photo_url` text NULL,
  `provider` varchar(64) NULL,
  `images` longtext NULL,
  `reply` longtext NULL,
  `reply_time` bigint NULL,
  `hide` varchar(32) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  UNIQUE KEY `grp_author_url_lang` (`google_place_id`, `author_url`, `language`),
  KEY `grp_google_place_id` (`google_place_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `wp_grp_google_review_text` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `review_id` varchar(255) NOT NULL,
  `lang` varchar(32) NOT NULL,
  `text` longtext NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_review_lang` (`review_id`, `lang`),
  KEY `idx_review_id` (`review_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `wp_grp_google_stats` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `google_place_id` bigint unsigned NOT NULL,
  `time` bigint NOT NULL,
  `rating` double NULL,
  `review_count` bigint NULL,
  PRIMARY KEY (`id`),
  KEY `grp_google_place_id` (`google_place_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
""".strip()


def quote_identifier(value: str) -> str:
    if not SAFE_IDENTIFIER.fullmatch(value):
        raise ValueError(f"Unsafe SQL identifier: {value!r}")
    return f"`{value}`"


def sql_literal(value: Any) -> str:
    if value is None:
        return "NULL"
    if isinstance(value, bool):
        return "1" if value else "0"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, float):
        if not math.isfinite(value):
            raise ValueError(f"Non-finite float cannot be migrated: {value!r}")
        return repr(value)
    if isinstance(value, str):
        payload = value.encode("utf-8")
    elif isinstance(value, bytes):
        payload = value
    else:
        raise TypeError(f"Unsupported SQLite value type: {type(value).__name__}")
    return "X'" + payload.hex() + "'"


def file_sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def write_import(
    connection: sqlite3.Connection,
    output: TextIO,
    tables: list[str],
) -> dict[str, dict[str, Any]]:
    manifest: dict[str, dict[str, Any]] = {}
    output.write("-- Generated by migrate-wordpress-sqlite-to-mariadb.py\n")
    output.write("SET NAMES utf8mb4;\n")
    output.write("SET SQL_MODE='NO_AUTO_VALUE_ON_ZERO';\n")
    output.write("SET FOREIGN_KEY_CHECKS=0;\n")
    output.write(GOOGLE_REVIEW_TABLES + "\n")
    output.write("START TRANSACTION;\n")

    for table in tables:
        quoted_table = quote_identifier(table)
        columns = [
            row[1]
            for row in connection.execute(
                f"PRAGMA table_info({quoted_table})"
            ).fetchall()
        ]
        if not columns:
            raise ValueError(f"Source table has no columns: {table}")
        for column in columns:
            quote_identifier(column)

        count = connection.execute(
            f"SELECT COUNT(*) FROM {quoted_table}"
        ).fetchone()[0]
        manifest[table] = {"columns": columns, "rows": count}

        output.write(f"DELETE FROM {quoted_table};\n")
        quoted_columns = ",".join(quote_identifier(column) for column in columns)
        cursor = connection.execute(f"SELECT * FROM {quoted_table}")
        for row in cursor:
            values = ",".join(sql_literal(value) for value in row)
            output.write(
                f"INSERT INTO {quoted_table} ({quoted_columns}) VALUES ({values});\n"
            )

    output.write("COMMIT;\n")
    output.write("SET FOREIGN_KEY_CHECKS=1;\n")
    return manifest


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("source", type=Path)
    parser.add_argument("output", type=Path)
    parser.add_argument("--manifest", type=Path)
    parser.add_argument("--prefix", default="wp_")
    args = parser.parse_args()

    source = args.source.resolve(strict=True)
    output = args.output.resolve()
    manifest_path = (
        args.manifest.resolve()
        if args.manifest
        else output.with_suffix(output.suffix + ".json")
    )
    if output.exists() or manifest_path.exists():
        raise SystemExit("Refusing to overwrite an existing migration artifact")
    output.parent.mkdir(parents=True, exist_ok=True)
    manifest_path.parent.mkdir(parents=True, exist_ok=True)

    with sqlite3.connect(f"file:{source}?mode=ro", uri=True) as connection:
        check = connection.execute("PRAGMA quick_check").fetchone()
        quick_check = check[0] if check else "no result"
        if quick_check != "ok":
            raise SystemExit(f"Source database failed quick_check: {quick_check}")
        tables = [
            row[0]
            for row in connection.execute(
                "SELECT name FROM sqlite_master "
                "WHERE type='table' AND name LIKE ? "
                "AND name NOT LIKE '\\_wp\\_sqlite\\_%' ESCAPE '\\' "
                "ORDER BY name",
                (args.prefix + "%",),
            ).fetchall()
        ]
        if not tables:
            raise SystemExit("No WordPress tables found in the source database")
        with output.open("x", encoding="utf-8", newline="\n") as handle:
            table_manifest = write_import(connection, handle, tables)

    manifest = {
        "source": str(source),
        "source_sha256": file_sha256(source),
        "source_quick_check": quick_check,
        "output": str(output),
        "output_sha256": file_sha256(output),
        "tables": table_manifest,
        "total_rows": sum(item["rows"] for item in table_manifest.values()),
    }
    manifest_path.write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    print(json.dumps(manifest, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
